### DAY 1

# Data Analysis

- The meaningful information said to be data
- Types of data in realtime/devices
    - .txt,.doc,.xls,.ppt,.mp3,.mp4 etc
- Types of Data in realtime
    1. Quantitative and
        - Represents the size/volume of data
        - Discrete and ContinuouS
            - This type of data is fixed/constant
                - Ex: numbers on die:varies from 1 to 6
                    ~ distance,color,nationality,size etc
            - Continuous data means the value/data is continuous
                - height,weight & hours
    2. Qualitative
        - Data is observed and placed in terms of catergory
            - Ex: Data Submission in Feedback form
- Data in Statistics
    - Nominal,Ordinal,Interval and Ratio
        - Nominal means data is categorized on the basis of names
            - Ex: Nationality,Color,Gender
        - Ordinal means data is based upon the order of values
            - Feedback form
        - Interval means a range of data values
            - time interval in clock :2:15 is in b/w 2&3
        - Raio means data is meaningfuly added,subtracted,mutiplied or divided



In [ ]:
# sum of middle digits

n = list(map(int,input().split()))
s = 0
for i in n:
    mid = len(str(i))//2
    print("mid : ",mid)
    i = list(str(i))
    print("mid index value : ",i[mid])
    s = s+int(i[mid])

print("Sum of middle digits is : ",s)

## NUMPY 
### NUMERICAL PYTHON

In [2]:
#numpy array
import numpy as np

#array
print(np.array([1,2,3,4,5],dtype="float"))

# tuple
print(np.array((1,2,3,4,5)))

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [9]:
st = np.array([1.2,4.4,5,6,8.909,5],dtype="str")
print(st)

['1.2' '4.4' '5' '6' '8.909' '5']


In [6]:
a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a = np.array(range(10,80))
print(a)
print("----------------")
a = np.array(range(80,10,-3))
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
----------------
[80 77 74 71 68 65 62 59 56 53 50 47 44 41 38 35 32 29 26 23 20 17 14 11]


In [16]:
a.ndim


1

In [7]:
ta = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ta)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
ta.ndim

2

In [ ]:
ta.shape(row,coloum)

ta.size # no of elements in array

ta.datatype # data type

ta.itemsize 

In [8]:
d3 = np.array([[[1,2.02,3],[4,"hii",6]],[["a","b","c"],[4,"hii",6]]])
print(d3)

[[['1' '2.02' '3']
  ['4' 'hii' '6']]

 [['a' 'b' 'c']
  ['4' 'hii' '6']]]


In [9]:
d32 = np.array([1,2,3,4,5],ndmin=30) ## max 32
print(d32)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [20]:
i = np.eye(3,6)
print(i)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [17]:
z = np.zeros((3,4),dtype="float")

print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
d3.size

12

In [18]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [23]:
o= np.ones((4,6),dtype = "int")
print(o)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [25]:
f = np.full(7,"rizwan")
print(f)

['rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan']


In [26]:
f = np.full(99,"rizwan")
print(f)

['rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan' 'rizwan'
 'rizwan' 'rizwan' 'rizwan']


In [27]:
f.size

99

In [37]:
fu = np.full((6,6),"hey")
print(fu)

[['hey' 'hey' 'hey' 'hey' 'hey' 'hey']
 ['hey' 'hey' 'hey' 'hey' 'hey' 'hey']
 ['hey' 'hey' 'hey' 'hey' 'hey' 'hey']
 ['hey' 'hey' 'hey' 'hey' 'hey' 'hey']
 ['hey' 'hey' 'hey' 'hey' 'hey' 'hey']
 ['hey' 'hey' 'hey' 'hey' 'hey' 'hey']]


In [38]:
fu.fill(12)
# fu.dtype="float"
print(fu)

[['12' '12' '12' '12' '12' '12']
 ['12' '12' '12' '12' '12' '12']
 ['12' '12' '12' '12' '12' '12']
 ['12' '12' '12' '12' '12' '12']
 ['12' '12' '12' '12' '12' '12']
 ['12' '12' '12' '12' '12' '12']]


In [34]:
# USING LINEAR SPACE

ln = np.linspace(10,100,17)
print(ln)

[ 10.     15.625  21.25   26.875  32.5    38.125  43.75   49.375  55.
  60.625  66.25   71.875  77.5    83.125  88.75   94.375 100.   ]


In [25]:
print(np.arange(1,100))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [27]:
print(np.arange(2,99,5))

[ 2  7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97]


In [28]:
print(np.arange(60,12,-2))

[60 58 56 54 52 50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14]


In [49]:
fu = fu.reshape(3,12)
print(fu)

[['12' '12' '12' '12' '12' '12' '12' '12' '12' '12' '12' '12']
 ['12' '12' '12' '12' '12' '12' '12' '12' '12' '12' '12' '12']
 ['12' '12' '12' '12' '12' '12' '12' '12' '12' '12' '12' '12']]


In [43]:
fu.itemsize


12

In [53]:
arr = np.array([[1,2,3],[4,5,6],[11,4,2],[3,7,3]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [11  4  2]
 [ 3  7  3]]


In [54]:
arr = arr.reshape(6,2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11  4]
 [ 2  3]
 [ 7  3]]


In [13]:
# random module
# random integer in a range
import numpy as np

rn = np.random.randint(10)
print(rn)

3


In [39]:
rn = np.random.randint(20,65)
print(rn)

39


In [96]:
lw = 100 # lower range
up = 1000 # upper range
rn = np.random.randint(lw,up,12)
rn = rn.reshape(3,4)
print(rn)

[[987 643 934 454]
 [200 312 654 587]
 [380 912 261 670]]


In [97]:
rn.ndim


2

In [100]:
print(rn)

[[987 643 934 454]
 [200 312 654 587]
 [380 912 261 670]]


In [104]:
import math 

dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [108]:
r = np.random.random((3,4)) # 0 to 1
print(r)

[[0.54374034 0.35347083 0.20708078 0.11671423]
 [0.44407867 0.78986102 0.51651067 0.01984212]
 [0.51082107 0.02087465 0.40592195 0.0163048 ]]


In [113]:
r = np.random.rand(2,2) # 0 to 1
print(r)

[[0.53165579 0.18694467]
 [0.19227672 0.31420667]]


In [117]:
r = np.random.randn(3,3) # -1 to 1
print(r)

[[ 0.59692904 -0.45409349  0.28495068]
 [-0.38706776 -0.45466921  0.15679738]
 [ 1.50087396  0.02048711 -0.96964271]]


In [128]:
r = np.linspace(10,11,10)
print(r)

[10.         10.11111111 10.22222222 10.33333333 10.44444444 10.55555556
 10.66666667 10.77777778 10.88888889 11.        ]


help(np.linspace)

#### Accesing the array elements 
- using index
- index is of 3 types
- +ve,-ve & fancy indexing
    - +ve index : traverse from left to right starts from 0 to len(it)-1
    - -ve index : traverse from right to left starts from -1 upto -ve infinite
    - fancy : condition based indexing
    

In [129]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[7,8,9],[2,5,7],[1,2,3]])
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [2 5 7]
 [1 2 3]]


In [134]:
r = np.random.randint(50,200,25).reshape(5,-1)
print(r)

[[ 98 143  69  66 124]
 [131  87 156 115 121]
 [ 97  82  80  54 187]
 [ 74  72 112  85 139]
 [ 80 171  77 191  63]]


In [148]:
r1 = np.arange(50,100,2).reshape(-3,5)
print(r1)

[[50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [143]:
r1[3]

array([80, 82, 84, 86, 88])

In [149]:
r1[:]

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [150]:
r1[::]

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [151]:
r1[::2]

array([[50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [157]:
r1[:,1:4]

array([[52, 54, 56],
       [62, 64, 66],
       [72, 74, 76],
       [82, 84, 86],
       [92, 94, 96]])

In [154]:
r1[::3]

array([[50, 52, 54, 56, 58],
       [80, 82, 84, 86, 88]])

In [155]:
r1


array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [158]:
for i in r1:
    print(i)
    for j in i:
        print(j)

[50 52 54 56 58]
50
52
54
56
58
[60 62 64 66 68]
60
62
64
66
68
[70 72 74 76 78]
70
72
74
76
78
[80 82 84 86 88]
80
82
84
86
88
[90 92 94 96 98]
90
92
94
96
98


In [159]:
r1[1:4:2,1:4:2]

array([[62, 66],
       [82, 86]])

In [160]:
r1

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [161]:
## alternae rows and cols
r1[::2,::2]

array([[50, 54, 58],
       [70, 74, 78],
       [90, 94, 98]])

In [162]:
r1.transpose()

array([[50, 60, 70, 80, 90],
       [52, 62, 72, 82, 92],
       [54, 64, 74, 84, 94],
       [56, 66, 76, 86, 96],
       [58, 68, 78, 88, 98]])

In [163]:
r1<10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [164]:
r1>100

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [166]:
r1[r1>80]

array([82, 84, 86, 88, 90, 92, 94, 96, 98])

In [175]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[5,3,4],[6,1,2]])
# print(a1)
# print(a2)
print(a1**a2)

[[   1    8   81]
 [4096    5   36]]


In [176]:
a3 = np.random.rand(4,4)
print(a3)

[[0.14709393 0.2736167  0.57618391 0.67413059]
 [0.03939498 0.86268288 0.67797374 0.65543619]
 [0.78636322 0.09693706 0.24335051 0.60380138]
 [0.5776508  0.33016677 0.0018579  0.5886259 ]]


In [208]:
a3 = np.random.randint(10,225,16).reshape(4,4)
print(a3)

[[185 166 147  53]
 [182  72  83 224]
 [164  76 223 198]
 [ 92  57  70 129]]


In [180]:
a3.min()

187

In [181]:
a3.max()

992

In [182]:
print(a3)

[[717 913 192 187]
 [274 609 599 649]
 [608 753 583 306]
 [879 992 786 942]]


In [185]:
a3

array([[717, 913, 192, 187],
       [274, 609, 599, 649],
       [608, 753, 583, 306],
       [879, 992, 786, 942]])

In [245]:
a3 = np.random.randint(7667,4747438,16).reshape(4,4)
print(a3)
print(a3.min())
print(a3.max())

[[3750405 3864368 1630927 1668474]
 [1574816 2876961 3812407 2456224]
 [1277649 1070339 4358369 4616551]
 [4295925 3263024  227628 3774188]]
227628
4616551


In [253]:
np.log(100)

2.0

In [248]:
np.log(0)

<ipython-input-248-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [254]:
np.exp(np.log(10))

10.000000000000002

In [257]:
np.log10(np.exp(10))

4.342944819032518

In [262]:
## program

def maxi(a,b):
#     print(a)
#     print(b)
    for i in range(len(a)):
        if a[i]>b[i]:
            print(a[i],end=" ")
        else:
            print(b[i],end=" ")
            
maxi([9,3,1],[4,10,4])

9 10 4 

### VECTORIZED FUNCTIONS IN NUMPY

In [264]:
def greater(a,b):
    if a>b:
        return a
    else:
        return b

g = np.vectorize(greater)
g([9,3,1],[4,10,4])

array([ 9, 10,  4])

In [265]:
help(np.vectorize)

Help on class vectorize in module numpy:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns a single numpy array or a tuple of numpy
 |  arrays. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optional
 |      The 